

const TRANSACTION_TYPE_DEPOSIT = 1;
const TRANSACTION_TYPE_WITHDRAW = 2;

const WALLET_STATUS_DISABLED = 0;
const WALLET_STATUS_ENABLED = 1;

module.exports = {
    TRANSACTION_TYPE_DEPOSIT,
    TRANSACTION_TYPE_WITHDRAW,
    WALLET_STATUS_DISABLED,
    WALLET_STATUS_ENABLED
};